name: eeg-env

dependencies:
  - python >=3.7
  - pip
  - conda-build
  - conda-verify
  - conda-lock
  - setuptools_scm
  - toml
  - ipython

  # Package dependencies
  - matplotlib
  - pandas
  - pip
  - python
  - scikit-learn
  - miniconda
  - mne
  - pyqt5

  # Misc
  - black
  - jupyterlab
  - pre-commit
  - snakeviz
  - tox-conda

